version: "3.9"
services:
  web:
    build: .
    ports:
      - "8090:5000"
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5  
